# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/data.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13protobuf/data.proto\x12\x04main\"\x1f\n\rProtoImageRow\x12\x0e\n\x06values\x18\x01 \x03(\x02\"3\n\x0eProtoImageData\x12!\n\x04rows\x18\x01 \x03(\x0b\x32\x13.main.ProtoImageRow\"<\n\x08ProtoDWT\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.main.ProtoImageDatab\x06proto3')
)




_PROTOIMAGEROW = _descriptor.Descriptor(
  name='ProtoImageRow',
  full_name='main.ProtoImageRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='main.ProtoImageRow.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=60,
)


_PROTOIMAGEDATA = _descriptor.Descriptor(
  name='ProtoImageData',
  full_name='main.ProtoImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='main.ProtoImageData.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=113,
)


_PROTODWT = _descriptor.Descriptor(
  name='ProtoDWT',
  full_name='main.ProtoDWT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='main.ProtoDWT.mode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='main.ProtoDWT.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=175,
)

_PROTOIMAGEDATA.fields_by_name['rows'].message_type = _PROTOIMAGEROW
_PROTODWT.fields_by_name['data'].message_type = _PROTOIMAGEDATA
DESCRIPTOR.message_types_by_name['ProtoImageRow'] = _PROTOIMAGEROW
DESCRIPTOR.message_types_by_name['ProtoImageData'] = _PROTOIMAGEDATA
DESCRIPTOR.message_types_by_name['ProtoDWT'] = _PROTODWT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoImageRow = _reflection.GeneratedProtocolMessageType('ProtoImageRow', (_message.Message,), dict(
  DESCRIPTOR = _PROTOIMAGEROW,
  __module__ = 'protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:main.ProtoImageRow)
  ))
_sym_db.RegisterMessage(ProtoImageRow)

ProtoImageData = _reflection.GeneratedProtocolMessageType('ProtoImageData', (_message.Message,), dict(
  DESCRIPTOR = _PROTOIMAGEDATA,
  __module__ = 'protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:main.ProtoImageData)
  ))
_sym_db.RegisterMessage(ProtoImageData)

ProtoDWT = _reflection.GeneratedProtocolMessageType('ProtoDWT', (_message.Message,), dict(
  DESCRIPTOR = _PROTODWT,
  __module__ = 'protobuf.data_pb2'
  # @@protoc_insertion_point(class_scope:main.ProtoDWT)
  ))
_sym_db.RegisterMessage(ProtoDWT)


# @@protoc_insertion_point(module_scope)
