// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/data.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoImageRow struct {
	Values               []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProtoImageRow) Reset()         { *m = ProtoImageRow{} }
func (m *ProtoImageRow) String() string { return proto.CompactTextString(m) }
func (*ProtoImageRow) ProtoMessage()    {}
func (*ProtoImageRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_04c84de1bc8ed4fc, []int{0}
}

func (m *ProtoImageRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoImageRow.Unmarshal(m, b)
}
func (m *ProtoImageRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoImageRow.Marshal(b, m, deterministic)
}
func (m *ProtoImageRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoImageRow.Merge(m, src)
}
func (m *ProtoImageRow) XXX_Size() int {
	return xxx_messageInfo_ProtoImageRow.Size(m)
}
func (m *ProtoImageRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoImageRow.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoImageRow proto.InternalMessageInfo

func (m *ProtoImageRow) GetValues() []float32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type ProtoImageData struct {
	Rows                 []*ProtoImageRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProtoImageData) Reset()         { *m = ProtoImageData{} }
func (m *ProtoImageData) String() string { return proto.CompactTextString(m) }
func (*ProtoImageData) ProtoMessage()    {}
func (*ProtoImageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_04c84de1bc8ed4fc, []int{1}
}

func (m *ProtoImageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoImageData.Unmarshal(m, b)
}
func (m *ProtoImageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoImageData.Marshal(b, m, deterministic)
}
func (m *ProtoImageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoImageData.Merge(m, src)
}
func (m *ProtoImageData) XXX_Size() int {
	return xxx_messageInfo_ProtoImageData.Size(m)
}
func (m *ProtoImageData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoImageData.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoImageData proto.InternalMessageInfo

func (m *ProtoImageData) GetRows() []*ProtoImageRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ProtoDWT struct {
	Mode                 string          `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Data                 *ProtoImageData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProtoDWT) Reset()         { *m = ProtoDWT{} }
func (m *ProtoDWT) String() string { return proto.CompactTextString(m) }
func (*ProtoDWT) ProtoMessage()    {}
func (*ProtoDWT) Descriptor() ([]byte, []int) {
	return fileDescriptor_04c84de1bc8ed4fc, []int{2}
}

func (m *ProtoDWT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoDWT.Unmarshal(m, b)
}
func (m *ProtoDWT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoDWT.Marshal(b, m, deterministic)
}
func (m *ProtoDWT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoDWT.Merge(m, src)
}
func (m *ProtoDWT) XXX_Size() int {
	return xxx_messageInfo_ProtoDWT.Size(m)
}
func (m *ProtoDWT) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoDWT.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoDWT proto.InternalMessageInfo

func (m *ProtoDWT) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *ProtoDWT) GetData() *ProtoImageData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoImageRow)(nil), "main.ProtoImageRow")
	proto.RegisterType((*ProtoImageData)(nil), "main.ProtoImageData")
	proto.RegisterType((*ProtoDWT)(nil), "main.ProtoDWT")
}

func init() { proto.RegisterFile("protobuf/data.proto", fileDescriptor_04c84de1bc8ed4fc) }

var fileDescriptor_04c84de1bc8ed4fc = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0xf3, 0x84, 0x58, 0x72, 0x13,
	0x33, 0xf3, 0x94, 0xd4, 0xb9, 0x78, 0x03, 0x40, 0x5c, 0xcf, 0xdc, 0xc4, 0xf4, 0xd4, 0xa0, 0xfc,
	0x72, 0x21, 0x31, 0x2e, 0xb6, 0xb2, 0xc4, 0x9c, 0xd2, 0xd4, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d,
	0xa6, 0x20, 0x28, 0x4f, 0xc9, 0x92, 0x8b, 0x0f, 0xa1, 0xd0, 0x25, 0xb1, 0x24, 0x51, 0x48, 0x9d,
	0x8b, 0xa5, 0x28, 0xbf, 0x1c, 0xa2, 0x8e, 0xdb, 0x48, 0x58, 0x0f, 0x64, 0x9e, 0x1e, 0x8a, 0x61,
	0x41, 0x60, 0x05, 0x4a, 0x1e, 0x5c, 0x1c, 0x60, 0x61, 0x97, 0xf0, 0x10, 0x21, 0x21, 0x2e, 0x96,
	0xdc, 0xfc, 0x94, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x83, 0x8b,
	0x05, 0xe4, 0x2e, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x11, 0x74, 0x83, 0x40, 0x96, 0x05,
	0x81, 0x55, 0x24, 0xb1, 0x81, 0x9d, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x94, 0xd1, 0x58,
	0x87, 0xd1, 0x00, 0x00, 0x00,
}
